[build]
builder = "DOCKERFILE"
dockerfilePath = "deployment/Dockerfile"

[deploy]
startCommand = "python start_live_multi_coin_trading.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

