services:
  - type: web
    name: badshah-trading-bot
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TZ
        value: UTC
      - key: LIVE_TRADING_MODE
        value: "false"
      - key: PORT
        value: "10000"
    healthCheckPath: /health
    autoDeploy: true
