services:
  - type: web
    name: badshah-trading-bot
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TZ
        value: UTC
      - key: LIVE_TRADING_MODE
        value: false
    healthCheckPath: /health
    autoDeploy: true
