services:
  - type: web
    name: badshah-trading-bot
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: "pip install --no-cache-dir -r requirements_render.txt"
    startCommand: "python start_live_multi_coin_trading.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000

