services:
  - type: web
    name: badshah-trading-bot-advanced
    env: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true

