version: '3.8'

services:
  trading-bot:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: badshah-trading-bot
    restart: unless-stopped
    
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      # Risk Management
      - MAX_DAILY_LOSS_PCT=2.0
      - MAX_LOSS_PER_TRADE_PCT=1.0
      - EMERGENCY_STOP_LOSS_PCT=5.0
      - POSITION_SIZE_PCT=1.0
    
    volumes:
      # Persist logs and reports
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./data:/app/data
      # Mount config for easy updates
      - ../config:/app/config:ro
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 512M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/logs/multi_coin_trading.log') else 1)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Monitoring with Prometheus (uncomment if needed)
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus-data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'

  # Optional: Grafana for visualization (uncomment if needed)
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   volumes:
  #     - grafana-data:/var/lib/grafana

# volumes:
#   prometheus-data:
#   grafana-data:


