auto_optimize_max_iters: 16
auto_optimize_trials: 1012
backfill_candles: 2000
backtest_pass_max_mdd: 5.0
backtest_pass_min_pnl: 0.5
backtest_pass_min_roi: 0.5
backtest_pass_min_sharpe: 0.0
connectivity_check: false
cpu_limit_pct: 0
exchange: binance
fee_pct: 0.05
gbm_dt_ms: 150
gbm_mu: 0.0
gbm_sigma: 0.03
interval: 1m
latency_ms: 150
leverage: 1
log_dir: src/data/logs
max_drawdown_threshold_pct: 5.0
max_loss_per_trade: 0.005
min_seconds_between_reopt: 38
min_ticks_between_reopt: 327
min_trades_for_reopt: 150
model_dir: src/data/models
performance_window_trades: 300
profit_threshold_pct: 0.5
ram_limit_pct: 0
reconnect_backoff_seconds: 5
resource_check_interval_sec: 5
rest_poll_interval_ms: 1000
risk_per_trade_pct: 0.25
simulate_mode: offline
simulate_seed: 842757
slippage_pct: 0.01
starting_balance: 10000.0
strategy_dir: src/strategies
symbols:
- BTCUSDT
- ETHUSDT
volatility_trigger_threshold: 0.0
websocket_enabled: false
wfo_slices: 8
wfo_top_n: 5
